language: node_js
node_js:
  - "0.11"
  - "0.10"

env:
  global:
    secure: "dWLgXWL7zoT9Wli8BRCY8vLgmhjF52v+NT2+kFdrfReMhzXuqhBGfMx6wr0TmbQOzYj4EMvGINHD9k9B+GxoCuDKfc9KTRbFcp7Px5QrSTjSJEk/IvrvRsB7SEhJ/xvEMXgsQu9KZthWhU5E+t0lHPcUsGFFJWbTMCDrF85fO2I="

addons:
  code_climate:
    repo_token:
      secure: "W60vAQsqOrCnkjfoDYSc7VWyB9lc9BiDOzL5eXsTq7+cHz2R5//LwTDQnR1HvvxXQE/hnTL6/Wy/zDr0HAJCUWJy2tDa/SZl9NnBy9XInVArRpYaphAJhF7SCKvgaitptSejhoq4pWENzAenYi//v1prkm7QcdtegzkN0/UH4uQ="

before_install:
  - npm install -g grunt-cli