language: node_js
node_js:
  - "0.11"
  - "0.10"

addons:
 code_climate:
  repo_token: 53c6731269568016cf01bdba

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive